// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Siagri.Clima.Data.Context;

namespace Siagri.Clima.Data.Migrations
{
    [DbContext(typeof(SiagriContext))]
    partial class SiagriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Siagri.Clima.Business.Entities.Localidade", b =>
                {
                    b.Property<Guid>("LocalidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemperaturaAtual")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalidadeId");

                    b.HasIndex("LocalidadeId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("Siagri.Clima.Business.Entities.Localidade", b =>
                {
                    b.OwnsOne("Siagri.Clima.Business.VOs.CidadeVO", "Cidade", b1 =>
                        {
                            b1.Property<Guid>("LocalidadeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .HasColumnName("Nome")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LocalidadeId");

                            b1.ToTable("Localidades");

                            b1.WithOwner()
                                .HasForeignKey("LocalidadeId");
                        });

                    b.OwnsOne("Siagri.Clima.Business.VOs.CoordenadaVO", "Coordenada", b1 =>
                        {
                            b1.Property<Guid>("LocalidadeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Latitude")
                                .HasColumnName("Latitude")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Longitude")
                                .HasColumnName("Longitude")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LocalidadeId");

                            b1.ToTable("Localidades");

                            b1.WithOwner()
                                .HasForeignKey("LocalidadeId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
