version: '3.4'

services:
  sql:
    image: renanfssilva/sql:latest
    container_name: sql
    restart: "always"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Banco123
  climaapi:
    build: .
    image: renanfssilva/desafio-conexa:latest
    ports:
      - "5000:5000"
